### ISSUE TITLE
PHP allows recursion more than at depth 100

### ISSUE THREAD

**Issue by maxhopei** [kapolos/pramda#4]
In your readme file you say:

> While PHP does not support tail recursion and blows its stack at a depth of 100, we can use the trampoline technique to avoid using the stack for each invokation.

PHP allows recursion more than at depth 100. It's xdebug who blows the stack at a depth 100.
Please, see "xdebug.max_nesting_level" options at http://xdebug.org/docs/all_settings.

**Comment by kapolos** [comment]
Thank you for pointing this out - you are right that the hard limit of 100 is set by XDebug. Please note that the PHP [manual](https://secure.php.net/manual/en/functions.user-defined.php) says:

> Note: Recursive function/method calls with over 100-200 recursion levels can smash the stack and cause a termination of the current script.

I have edited the README to clarify that: 52eb027352bb0366e6f075d42db5ae8acf0ec286 

Thanks again!
