### ISSUE TITLE
How Pramda does compare to Phamda?

### ISSUE THREAD

**Issue by kapooostin** [kapolos/pramda#5]
https://github.com/mpajunen/phamda

**Comment by kapolos** [comment]
I was not aware of `phamda`, nice! From a quick first look look, `Pramda` supports `lazy evaluation` while `Phamda` does not and `Phamda` has implemented `placeholders` while `Pramda` has not.

**Comment by kapooostin** [comment]
Yes. Also Phamda demands php 5.6+.
