### ISSUE TITLE
Pramda vs Phamda vs imperative code

### ISSUE THREAD

**Issue by mmikeyy** [kapolos/pramda#9]
Hi, I like the idea behind this library a lot. PHP is so boring when compared with Javascript...

The library is fun to use, but it seems to come with a hefty performance penalty. I tested the example given in the documentation, the one in which we find the five words with the highest frequency in some text.

With fake latin text including 188 different words for a total of 1087 words, the results are as follows for Pramda vs Phamda vs imperative code:

Pramda: 15499 ms (yes, over 15 seconds...)
Phamda: 47 ms
imperative: 10.3 ms

The code is as follows, and all functions are provided the text in a string.

Note that I changed the code proposed in the example to make is as similar as possible to the Phamda code used. The code in the example executes in the same amount of time anyway.

``` PHP

use Phamda\Phamda as PP

$content = file_get_contents(<filename>);
$onlyWords = function ($txt) {
    return preg_split("/[^A-Za-z]/", $txt, NULL, PREG_SPLIT_NO_EMPTY);
};

//Pramda:
$start = microtime(true);
$fn = P::pipe(
    'strtolower',
    $onlyWords,
    P::countBy('P::identity'),
    P::sort('P::negate'),
    P::map(function($val, $key){return "$key: $val";}),
    P::take(5),
    'P::toArray');
print_r($fn($content));
echo "\n\n" . 1000 * (microtime(true) - $start) . ' ms (Pramda)' . "\n";

//******************* now Phamda
$start = microtime(true);
$fn = PP::pipe(
    'strtolower',
    $onlyWords,
    PP::groupBy(PP::identity()),
    PP::map(function($list, $word){return [$word, count($list)];}),
    PP::sort(function($a, $b){return $b[1] <=> $a[1];}),
    PP::slice(0, 5),
    PP::map(function($list){list($word, $nb) = $list;return "$word: $nb";})
);
print_r($fn($content));
echo "\n\n" . 1000*(microtime(true) - $start) . " ms  (Phamda) \n\n";

//********************* now standard imperative code
$start = microtime(true);
$words = $onlyWords(strtolower($content));
$freq = [];
foreach($words as $word){
    if (array_key_exists($word, $freq)){
        $freq[$word]++;
    } else {
        $freq[$word] = 1;
    }
}
asort($freq);
print_r(array_reverse(array_slice($freq, -5)));
echo "\n\n" . 1000*(microtime(true) - $start) . " ms (imperative)\n\n";
```

Let me know if there's something I'm totally missing here...

**Comment by kapolos** [comment]
I will investigate properly, but in the mean time could you please run the benchmark with `P::file` instead of `file_get_contents`?

**Comment by mmikeyy** [comment]
The original example was run with P::file and took just as long (15 s).
But here is a test with the following code. I timed it by adding the operations in the pipe one at a time, and in the comment next to each one, I indicate the time it took to run the code when this operation is the last one in the list. (correction: 'P::toArray' is always added at the end as otherwise the results are meaningless...)

``` PHP
$text = P::file(<filename>);
$start = microtime(true);
$fn = P::pipe(
    P::map(P::compose($onlyWords, P::unary('strtolower'))) // takes 150 ms
    ,'P::flatten' // total time = 220 ms (so adds 70 ms)
    ,P::countBy('P::identity') // total time = 4535 ms (so adds 4315 ms)
    ,P::sort('P::negate') // total time = 15935 ms (so adds 11.4 s)
    ,P::map(function($val, $key){return "$key: $val";}) // total time = 16325ms (so adds 390ms)
    ,P::take(5) // total time = 15932 ms (so makes the sequence slightly  quicker...)
    ,'P::toArray' // this operation never commented out
);

$a = $fn($text);
echo "\n\n" . 1000 * (microtime(true) - $start) . ' ms pour composition 3' . "\n";
print_r($a);
```

I ran the tests several times and obtained the same results.

Finally, here is the content of the text file used for the test: [pastebin](http://pastebin.com/raw/H5237S5r)

**Comment by kapolos** [comment]
I tested with your code and text (9 lines & ~1000 words) and it took ~350ms (see screenshot below)

![speed_test1](https://cloud.githubusercontent.com/assets/10794126/15367866/93c244f0-1d33-11e6-8734-f055e80cbaf1.png)

`PHP 5.6.2 (cli) / Windows`

I also tested with a text file that had ~3700 lines and ~30 thousand words. For that, it took ~ 8sec. I am extremely hard-pressed today, but I will definitely investigate properly at first chance.

Thank you very much for reporting this and for giving Pramda a chance :+1: :beers:

**Comment by mmikeyy** [comment]
Hmm... this is surprising... Here's an idea. When I first started testing the library, I had a big problem with warnings generated by the library itself. They were so numerous that the terminal window displayed a message saying that there were too many to process. Here is the message that is repeated a nearly infinite number of times:

Deprecated: Non-static method P::_curry() should not be called statically in G:\www\ng2\srv\PHP\vendor\kapolos\pramda\src\pramda.php on line 598

Normally, I leave 'display-errors' off in development. But just because of Pramda, I had to set it off.

I edited the pramda.php file and made the _curry method static. The execution time went from 15 seconds to 1 second (1018 ms). I think leaving deprecated code in the library adds a lot to execution time (I'm using PHP 7).

I don't know if there's a reason for _curry to be non-static. That's for you to figure out. Perhaps my fix will explode in my face later...

OK, so now the comparison with Phamda is 20 to 1 in terms of execution time ratio (in favor of Phamda...), which is much better than the 150 to 1 ratio I had with the deprecated function call. 20 to 1 is still a bit perplexing I must say...

**Comment by kapolos** [comment]
I am a bit confused. There is no `_curry` method :exclamation: 

I just greped both branch `0.9.0` and `master` and can't find any match for `_curry`. Could you please provide more info?

**Comment by mmikeyy** [comment]
Here's another update...

I am testing on my local server. I have xdebug. I edited my configuration to switch xdebug profiler off for these tests. What a difference!

With xdebug-profiler off, the times goes down from 1000 ms to 100 ms.

And for Phamda, the time is down to 9 ms. So we now have a 10 to 1 ratio, but the time is more reasonable now...

Just saw your reply pop up above. I installed using composer from PHP-Storm, which reports installed version 0.10.x-dev.

Lines 2395 and following:

``` php
/**
     * Recursive currying
     *
     * Code based on: https://github.com/camspiers/php-fp/blob/master/src/fp.php
     *
     * @param callable $callable The callable
     * @param array    $args     The callable's arguments
     * @param integer  $arity    The callable's arity
     *
     * @return callable
     */
    private static function _curry(callable $callable, $args, $arity) // I ADDED STATIC HERE
    {

        return function () use ($callable, $args, $arity) {
            $arguments = func_get_args();
            $args = array_merge($args, $arguments);

            if (count($args) >= $arity) {
                return call_user_func_array($callable, $args);
            } else {
                return self::_curry($callable, $args, $arity);
            }
        };
    }
```

**Comment by kapolos** [comment]
Ah, sorry about that, the `0.10` branch is still work in progress, that's why the master is still the `0.9` version. Indeed, I have replaced the curry function of `0.9`/`master` with the implementation above for `0.10`. But I did not test for speed, generally because I have left speed optimization as a lower priority goal. But certainly, if the change introduces significant delay, I will revert it.

Is the speed behavior in your benchmark the same when using the `0.9`/`master` version as well?

**Comment by mmikeyy** [comment]
OK my bad! Had not noticed that I had installed from the 0.10 branch. (you can see _curry there).

Installed 0.9.0 now. No deprecated code warning. The latest results I reported above are still good:

Pramda: 108 ms. 
Phamda: 12 ms.
Imperative code, if you're curious: 1.6 ms

The problem of 0.10 as opposed to 0.9 is the deprecated code (only that _curry method). If that is fixed, there is no difference.

Phamda is 8 times slower than imperative code. Pramda is apparently 9 times slower than Phamda. (for the functions tested above anyway...)

We're far from the timing values I had at the beginning, but the timing ratios I get between the different tools & methods lead me to conclude that functional programming in PHP comes with such a high performance penalty that its advantages should always be weighed against its benefits in every situation. I'd love to be wrong about this because functional programming _is_ fun!

**Comment by kapolos** [comment]
`1 / 10 / 100` sounds reasonable to me. Functional programming can't be as fast as imperative due to the necessary overhead and Pramda is completely unoptimized for speed at this point. 

My first goal was for the code to be easily readable and "eat its own dogfood", because for now, there is not much else someone can refer to when trying to work with the library. 

But at the same time, it can't be too slow if it is going to be widely usable. I think `0.11` should be a good time to focus on speed. Very open to suggestions/improvements.
